FROM node

RUN mkdir -p /home/app

COPY ./app /home/app

WORKDIR /home/app

# run this command if you ignored node_modules in .dockerignore
# RUN npm install
# EXPOSE 3001

CMD [ "node", "src/index.mjs" ]