version: '3'

services:
  app:
    # build: .
    image: my_app:latest
    ports:
      - 3000:3000

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=modex98
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-my-app:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=modex98
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo-my-app:
    driver: local